Updated README.md with parallel info
EvanForsythe/ERCnet pull request #32
Opened 2022-06-29 20:14 UTC by tgattsIV

Updates option flags for Phylogenomics.py with -c / --core_distribution flags for parallel processing. Also defines the core distribution groups in a table below.

2022-06-29 22:12 UTC, EvanForsythe requested changes
Looks good to me! I like the table you made with groups and cores. The one issue I found is that we'll need the user to install the joblib module (ideally using conda). Please add a instructions for installing joblib with conda (add it with all the other conda commands). Here's what I used that seems to have worked for me: "conda install -c conda-forge joblib".

2022-06-29 23:09 UTC, tgattsIV commented
Oh right, I totally forgot I had to install that, I'll add the info into the other conda commands tomorrow!

2022-07-09 16:21 UTC, EvanForsythe commented
The readme looks great! I noticed a couple small issues... I think there may be a typo in your front end/back end table. Should 2 be 4 in the bottom row of the table? Also, I'd like to use conda to install joblib instead of pip. I've read that combining pip and conda can break things. I've tested "conda install -c conda-forge joblib" and it seems to work fine for my setting up my conda environment so please put that in the readme instead of the pip line. Thanks!

2022-07-14 21:45 UTC, EvanForsythe approved these changes

2022-07-14 21:49 UTC, merged